const $=s=>document.querySelector(s);let client='',user={name:'',room:''},stopped=false,typingTimer;
const joinView=$('#joinView'),chatView=$('#chatView'),messages=$('#messages'),input=$('#messageInput');$('#nameInput').value=localStorage.getItem('pulse-name')||'';
const post=async(path,data={})=>{const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
function initials(n){return n.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}function safe(el,text){el.textContent=text;return el}
function showEmpty(){messages.innerHTML='<div class="empty"><div><strong>Start the conversation</strong>No messages in this room yet.</div></div>'}function removeEmpty(){messages.querySelector('.empty')?.remove()}
function renderMessage(d){removeEmpty();const row=document.createElement('article');row.className='message';const av=safe(document.createElement('div'),initials(d.name));av.className='avatar';const box=document.createElement('div'),head=document.createElement('div');head.className='message-head';const name=safe(document.createElement('span'),d.name);name.className='message-name';const time=safe(document.createElement('time'),new Date(d.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));time.className='message-time';const body=safe(document.createElement('div'),d.text);body.className='message-body';head.append(name,time);box.append(head,body);row.append(av,box);messages.append(row);messages.scrollTop=messages.scrollHeight}
function event(d){if(d.type==='message')renderMessage(d);else if(d.type==='system'){removeEmpty();const e=safe(document.createElement('div'),d.text);e.className='system-message';messages.append(e)}else if(d.type==='users')renderUsers(d.users);else if(d.type==='typing'){$('#typingText').textContent=d.users.filter(n=>n!==user.name).slice(0,1).map(n=>n+' is typing…')[0]||''}}
function renderUsers(users){$('#onlineCount').textContent=users.length;const list=$('#userList');list.innerHTML='';users.forEach(n=>{const row=document.createElement('div');row.className='user';const av=safe(document.createElement('div'),initials(n));av.className='avatar';const name=safe(document.createElement('span'),n);name.className='user-name';row.append(av,name);if(n===user.name){const y=safe(document.createElement('span'),'YOU');y.className='you';row.append(y)}list.append(row)})}
async function poll(){while(!stopped&&client){try{const r=await fetch('/api/poll?client='+encodeURIComponent(client));if(r.status===410)throw Error('Session expired');const d=await r.json();d.events.forEach(event);$('#statusText').textContent='Live now'}catch(e){$('#statusText').textContent='Reconnecting…';await new Promise(r=>setTimeout(r,1200))}}}
$('#joinForm').onsubmit=async e=>{e.preventDefault();$('#joinError').textContent='';user={name:$('#nameInput').value.trim(),room:$('#roomInput').value.trim().toLowerCase()};try{const d=await post('join',user);client=d.client;user.name=d.name;stopped=false;localStorage.setItem('pulse-name',user.name);$('#roomLabel').textContent=user.room;$('#headerRoom').textContent='# '+user.room;input.placeholder='Message #'+user.room;messages.innerHTML='';d.history.length?d.history.forEach(renderMessage):showEmpty();joinView.classList.add('hidden');chatView.classList.remove('hidden');$('#statusText').textContent='Live now';poll();input.focus()}catch(err){$('#joinError').textContent=err.message}};
$('#messageForm').onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;input.value='';resize();await post('message',{client,text})};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#messageForm').requestSubmit()}};input.oninput=()=>{resize();post('typing',{client,active:true}).catch(()=>{});clearTimeout(typingTimer);typingTimer=setTimeout(()=>post('typing',{client,active:false}).catch(()=>{}),900)};function resize(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,140)+'px'}
$('#leaveButton').onclick=()=>{stopped=true;post('leave',{client}).catch(()=>{});client='';chatView.classList.add('hidden');joinView.classList.remove('hidden');$('#sidebar').classList.remove('open')};$('#openSidebar').onclick=()=>$('#sidebar').classList.add('open');$('#closeSidebar').onclick=()=>$('#sidebar').classList.remove('open');
